"use client";

import { useEffect } from "react";
import { contentMessages } from "@/messages/content.pt-BR";
import styles from "./CheatSheetModal.module.scss";

const m = contentMessages.topic.actions;

export interface CheatSheetModalProps {
  /** HTML of the cheat sheet of the prototype ("Cola"). */
  html: string;
  onClose(): void;
}

/** Overlay with the cheat sheet of the prototype, reused as it is (SPEC-016, P-04). */
export function CheatSheetModal({ html, onClose }: CheatSheetModalProps) {
  useEffect(() => {
    const onKey = (event: KeyboardEvent) => {
      if (event.key === "Escape") onClose();
    };
    document.addEventListener("keydown", onKey);
    return () => document.removeEventListener("keydown", onKey);
  }, [onClose]);

  return (
    <div className={styles.backdrop} onClick={(event) => event.target === event.currentTarget && onClose()}>
      <div className={styles.modal} role="dialog" aria-modal="true" aria-label={m.cheatSheetTitle}>
        <header className={styles.header}>
          <h2 className={styles.title}>{m.cheatSheetTitle}</h2>
          <button type="button" className={styles.close} onClick={onClose} aria-label={m.close} title={m.close}>
            ✕
          </button>
        </header>
        {/* The cheat sheet HTML is generated by the prototype code from its own static content. */}
        <div className={styles.content} dangerouslySetInnerHTML={{ __html: html }} />
      </div>
    </div>
  );
}
