// Package data embeds the content manifest generated by the extractor
// (SPEC-005), so the seed command is self-contained.
package data

import _ "embed"

// Manifest is the gzip-compressed content manifest.
//
//go:embed content_manifest.json.gz
var Manifest []byte
